import argparse
import os
import re
import sys

def validate_name(name):
    """Ensure skill name is kebab-case (lowercase, numbers, hyphens)."""
    if not re.match(r'^[a-z0-9-]+$', name):
        print(f"Error: Skill name '{name}' must contain only lowercase letters, numbers, and hyphens.")
        sys.exit(1)
    return name

def create_skill_structure(name, description, output_dir, author, script_type):
    """Generate the standard skill directory structure."""
    skill_dir = os.path.join(output_dir, name)
    scripts_dir = os.path.join(skill_dir, "scripts")
    
    # 1. Create Directories
    os.makedirs(scripts_dir, exist_ok=True)
    print(f"Created directory: {skill_dir}")
    print(f"Created directory: {scripts_dir}")

    # 2. Generate SKILL.md
    skill_md_content = f"""---
name: {name}
description: {description}
author: {author}
version: 0.1.0
---

# {name} (Skill Title)

> **Goal**: {description}

## 1. Core Capabilities
- **Capability 1**: Describe what this skill does.
- **Capability 2**: Describe another feature.

## 2. Usage
### Interactive Mode
> "Help me {name.replace('-', ' ')}..."

### Manual Execution
```bash
# Example command
python scripts/main.py --arg value
```

## 3. Configuration (Optional)
- `ENV_VAR`: Description of environment variable.

## 4. Troubleshooting
- **Error 1**: Solution.
"""
    with open(os.path.join(skill_dir, "SKILL.md"), "w", encoding="utf-8") as f:
        f.write(skill_md_content)
    print(f"Generated: {os.path.join(skill_dir, 'SKILL.md')}")

    # 3. Generate README.md (Optional but recommended)
    readme_content = f"""# {name}

This is a standard skill generated by `standard-skill-generator`.

## Installation
Copy this folder to `.micode/skills/` or `~/.micode/skills/`.

## Usage
See `SKILL.md` for detailed instructions.
"""
    with open(os.path.join(skill_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme_content)
    print(f"Generated: {os.path.join(skill_dir, 'README.md')}")

    # 4. Generate Script Template (Optional)
    if script_type == "python":
        script_content = """import argparse

def main():
    parser = argparse.ArgumentParser(description="Core logic for the skill.")
    parser.add_argument("--input", help="Input argument")
    args = parser.parse_args()
    
    print(f"Hello from {name}! Input: {args.input}")

if __name__ == "__main__":
    main()
"""
        with open(os.path.join(scripts_dir, "main.py"), "w", encoding="utf-8") as f:
            f.write(script_content)
        print(f"Generated: {os.path.join(scripts_dir, 'main.py')}")
    elif script_type == "bash":
        script_content = """#!/bin/bash
echo "Hello from {name}!"
"""
        with open(os.path.join(scripts_dir, "main.sh"), "w", encoding="utf-8") as f:
            f.write(script_content)
        # Make executable (on Linux/Mac, but harmless on Windows)
        try:
            os.chmod(os.path.join(scripts_dir, "main.sh"), 0o755)
        except:
            pass
        print(f"Generated: {os.path.join(scripts_dir, 'main.sh')}")

    print(f"\nSkill '{name}' created successfully in '{skill_dir}'!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a standard Mi Code Skill structure.")
    parser.add_argument("--name", required=True, help="Skill name (kebab-case)")
    parser.add_argument("--description", required=True, help="Skill description for Agent discovery")
    parser.add_argument("--output-dir", default=".", help="Output directory (default: current)")
    parser.add_argument("--author", default="Mi Code User", help="Author name")
    parser.add_argument("--type", choices=["python", "bash", "none"], default="none", help="Script template type")
    
    args = parser.parse_args()
    
    validate_name(args.name)
    create_skill_structure(args.name, args.description, args.output_dir, args.author, args.type)
